<a href="https://colab.research.google.com/github/Pratyush-3226/mini_learning_projects/blob/main/assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([10,20,30,40,50,60,70,80,98,99])
print(a)

[10 20 30 40 50 60 70 80 98 99]


In [ ]:
print(np.max(a))

99


In [ ]:
print(np.min(a))

10


In [ ]:
print(np.mean(a))

55.7


In [ ]:
print(a.shape)
b=a.reshape(2,5)

(10,)


In [ ]:
print(a.ndim)

1


In [ ]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a=np.random.randint(1,100,20)
print(a)

[71 67 97 98 34 96 62 83 11 75 33 32 95 70 90 94 71 82 44 90]


In [ ]:
print(max(a))

98


In [ ]:
print(min(a))

11


In [ ]:
print(np.mean(a))

69.75


In [ ]:
print(np.median(a))

73.0


In [ ]:
print(np.std(a))

25.36508426952294


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
a=np.arange(2,50,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [ ]:
*Email Spam Detection*
-Application: Email services like Gmail and Outlook use ML to identify spam emails.
-Why ML is used: Spam messages constantly change. Machine learning learns from millions of emails and improves over time, making it more accurate at detecting new spam without needing manually written rules.
*Recommendation Systems*
-Application: Platforms like Netflix, YouTube, and Amazon recommend movies, videos, or products.
-Why ML is used: ML analyzes users' viewing or shopping history, preferences, and behavior to predict what they are most likely to enjoy or buy, providing personalized recommendations.
*Face Recognition*
-Application: Smartphones use face recognition to unlock devices, and social media platforms can identify people in photos.
-Why ML is used: Human faces vary due to lighting, angles, expressions, and aging. ML learns these patterns from many images, enabling accurate recognition under different conditions.
These applications use machine learning because it can learn